name: Release

on:
  push:
    tags:
      - v*.*.*

jobs:
  build:
    name: Build release
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')

    runs-on: ${{ matrix.os }}
    timeout-minutes: 15

    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.7]
        torch-version: [1.9.1]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install PyTorch ${{ matrix.torch-version }}+cpu
        run: |
          pip install torch==${{ matrix.torch-version}}+cpu -f https://download.pytorch.org/whl/torch_stable.html

      - name: Build package
        run: |
          python setup.py bdist_wheel sdist

      - name: Upload package distribution files
        uses: actions/upload-artifact@v3
        with:
          name: package
          path: dist

  deploy:
    name: Deploy release
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')

    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - uses: actions/checkout@v3

      - name: Download package distribution files
        uses: actions/download-artifact@v3
        with:
          name: package
          path: dist

      - name: Publish package to PyPI
        run: |
          twine upload -u __token__ -p ${{ secrets.PYPI_TOKEN }} dist/*
